### ISSUE TITLE
Output *.vsix files

### ISSUE THREAD

**Issue by felixjb** [lannonbr/vsce-action#3]
I would like this action to output the `*.vsix` files that are published to the marketplace so I can upload them to my releases in my project's repository

**Comment by johnallen3d** [comment]
You could consider using the `package` command to do this. I'm publishing a private extension to GitHub releases. Here's my workflow:

```yaml
name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ...
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package --allow-star-activation"
      - run: echo "name=$(ls | grep vsix | sort | tail -n 1)" >> $GITHUB_OUTPUT
        id: identify-package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.identify-package.outputs.name}}
```
