### ISSUE TITLE
Running vsce from a directory within the repo

### ISSUE THREAD

**Issue by cowtrix** [lannonbr/vsce-action#5]
My extension is within a subdirectory of the repository called `/narlang_vsCode/`

I'm trying to figure out how to publish the extension from within this subdirectory. My action currently looks like this:

```
- name: Set GITHUB_WORKSPACE env
      run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
- name: Publish VsCode Extension
      uses: lannonbr/vsce-action@master
      with:
          entryPoint: ${{ env.workspace }}/narlang_vsCode/
          args: "publish -p $VSCE_TOKEN"
      env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
```

I get this output:

```
/usr/bin/docker run --name cba8574651301f4b9c90c67d00d21062f9_dd7fa1 --label 8118cb --workdir /github/workspace --rm -e DOTNET_ROOT -e workspace -e VSCE_TOKEN -e INPUT_ENTRYPOINT -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/home/runner/work/narlang/narlang/narlang_vsCode/" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/narlang/narlang":"/github/workspace" 8118cb:a8574651301f4b9c90c67d00d21062f9 publish -p $VSCE_TOKEN
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/home/runner/work/narlang/narlang/narlang_vsCode/\": stat /home/runner/work/narlang/narlang/narlang_vsCode/: no such file or directory": unknown.
```

So obviously that isn't the way to do that. How would I?

**Comment by marabesi** [comment]
I am having the same issue

**Comment by marabesi** [comment]
in the end I just replaced the action with the manual execution:


```yml
name: Deploy Extension

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./vscode # subfolder that my extension was hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          npm install
          npm install -g vsce
          npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
```
